# MetaScribe Configuration (Default)

# Preprocessing
preprocessing:
  pdf_image_dpi: 200
  resize:
    skip: false
    max_image_width: 2000
    max_image_height: 2000
  binarization:
    skip: false
    jar_path: "resources/ZigZag.jar"

# Metadata Generation
metadata_generation:
  json_schema_path: "[FILL IN YOUR PATH]/ppa_examples/additional_generative_metadata.json"
  llm_model: "gemini-2.0-flash-001"
  system_prompt: "You are a metadata generator. Your task is to generate metadata from a given image and JSON schema.\n\nIMPORTANT: Do not speculate, infer, or add any information not directly present in the image."
  user_prompt: "Based on the image and JSON schema, generate metadata for the image."

# OCR
ocr:
  skip: false
  model: "gemini-2.0-flash-001"
  system_prompt: "You are an OCR assistant. Extract and return only the text from the image. Do NOT add any extra explanations, formatting, or special markdown commands. Output plain text only."
  user_prompt: "Extract and return the text from this image according to these principles:\n\n- Capture all Unicode-compatible characters, including symbols and special characters.\n- Preserve the author's intended meaning and formatting.\n- Do not correct grammar, spelling, or typographic errors—transcribe them exactly as they appear.\n\nDO NOT add any extra explanations, formatting, or special markdown commands."

# Aggregation
aggregation:
  skip: false
  llm_model: "gemini-2.0-flash-001"
  included_fields: ["page_summary", "uniqueness"]   # must correspond to the JSON schema fields under 'properties' in metadata_generation (using the keys)
  system_prompt: "You are a specialized document metadata processor creating summaries that will be converted to vector embeddings for semantic search. Your task is to produce summaries optimized for embedding performance.\n\nIMPORTANT: Only summarize information explicitly provided in the metadata fields. Do not speculate, infer, or add any information not directly present.\n\nGuidelines:\n- Create semantically dense sentences\n- Prioritize domain-specific terminology and key concepts\n- If relevant to the document, include specific entities and proper nouns\n- Minimize filler words and focus on content-rich language\n- Ensure conceptual completeness rather than stylistic elegance\n\nYour output must effectively capture the document's semantic essence for both human readers and vector-based retrieval systems."
  user_prompt: "Based on the following aggregated page-level document metadata, create a 3-4 sentence summary that captures the most essential elements.\n\nMinimize filler words and only summarize information explicitly provided in the metadata -- do not speculate, infer, or add any information not present.\n\nMake sure the summary is precisely 3-4 sentences long as it will be used to generate vector embeddings.\n\n--------------------\n\n"

  
